// This file will be generated by Python with template variables
// Configuration object for the map application
window.MAP_CONFIG = {
    center: [{{center_lat}}, {{center_lon}}],
    bounds: [[{{min_lat}}, {{min_lon}}], [{{max_lat}}, {{max_lon}}]],
    stadiaApiKey: '{{STADIA_API_KEY}}',
    openaipApiKey: '{{OPENAIP_API_KEY}}',
    dataDir: '{{data_dir_name}}'
};
