coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

comment:
  layout: "reach,diff,files,footer"
  behavior: default
  require_changes: false

ignore:
  - "tests/**"
  - "scripts/**"
  - "**/*.test.ts"
  - "**/*.test.js"
  - "**/mocks/**"
